[project]
name = "social-media-analysis"
version = "0.1.0"
description = "Course materials for social media analysis"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
dependencies = [
    "atproto>=0.0.71",
    "google-api-python-client>=2.199.0",
    "jupyterlab>=4.6.3",
    "python-dotenv>=1.2.3",
    "requests>=2.32.5",
]

[project.optional-dependencies]
docs = []

[dependency-groups]
docs = [
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-material>=9.7.0",
    "mkdocs-open-in-new-tab>=1.0.8",
]
